#!/usr/bin/env python3
"""Pack assets/tiles/ into the web sprite atlas.

  build.py        # writes web/sprites.png and web/sprites.js

Every dcss/*.png and gen/*.png becomes a one-frame sprite named after its
file; every anim/*.aseprite is exported through the Aseprite CLI and becomes
a multi-frame sprite with its per-frame durations. sprites.js carries the
atlas index plus the per-level wall/floor variant lists (sources.THEMES) for
web/tiles.js.
"""
import glob
import json
import os
import subprocess
import sys
import tempfile

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
TILES = os.path.join(ROOT, "assets", "tiles")
CELL, COLS = 32, 16

sys.path.insert(0, HERE)
from sources import THEMES  # noqa: E402


def export_anim(path):
    """Return ([frame images], [durations ms]) for an .aseprite file."""
    with tempfile.TemporaryDirectory() as tmp:
        sheet, data = os.path.join(tmp, "s.png"), os.path.join(tmp, "s.json")
        subprocess.run(["aseprite", "-b", path, "--sheet", sheet, "--sheet-type", "horizontal",
                        "--data", data, "--format", "json-array"], check=True,
                       stdout=subprocess.DEVNULL)
        meta = json.load(open(data))
        im = Image.open(sheet).convert("RGBA")
        frames, ms = [], []
        for f in meta["frames"]:
            r = f["frame"]
            frames.append(im.crop((r["x"], r["y"], r["x"] + r["w"], r["y"] + r["h"])))
            ms.append(f["duration"])
        return frames, ms


def main():
    sprites = {}  # name -> ([images], [ms])
    for sub in ("dcss", "gen"):
        for p in sorted(glob.glob(os.path.join(TILES, sub, "*.png"))):
            im = Image.open(p).convert("RGBA")
            if im.size != (CELL, CELL):
                sys.exit(f"{p}: {im.size}, want {CELL}x{CELL}")
            sprites[os.path.splitext(os.path.basename(p))[0]] = ([im], [0])
    for p in sorted(glob.glob(os.path.join(TILES, "anim", "*.aseprite"))):
        sprites[os.path.splitext(os.path.basename(p))[0]] = export_anim(p)

    cells = sum(len(f) for f, _ in sprites.values())
    rows = (cells + COLS - 1) // COLS
    atlas = Image.new("RGBA", (COLS * CELL, rows * CELL))
    index, n = {}, 0
    for name in sorted(sprites):
        frames, ms = sprites[name]
        coords = []
        for fr in frames:
            x, y = (n % COLS) * CELL, (n // COLS) * CELL
            atlas.paste(fr, (x, y))
            coords.append([x, y])
            n += 1
        index[name] = {"f": coords, "ms": ms if len(frames) > 1 else 0}

    themes = {}
    for level, (wall, floor) in THEMES.items():
        themes[level] = {
            "wall": sorted(k for k in index if k.startswith(wall + "_")),
            "floor": sorted(k for k in index if k.startswith(floor + "_")),
        }
        if not themes[level]["wall"] or not themes[level]["floor"]:
            sys.exit(f"theme {level}: no sprites for {wall}/{floor}")

    atlas.save(os.path.join(ROOT, "web", "sprites.png"), optimize=True)
    with open(os.path.join(ROOT, "web", "sprites.js"), "w") as f:
        f.write("// Generated by scripts/tiles/build.py from assets/tiles/ — do not edit.\n")
        f.write("window.TSL_SPRITES = ")
        json.dump({"cell": CELL, "sprites": index, "themes": themes}, f, separators=(",", ":"))
        f.write(";\n")
    print(f"{len(index)} sprites, {n} cells, atlas {atlas.size[0]}x{atlas.size[1]}")


if __name__ == "__main__":
    main()
